"""empty message

Revision ID: 263ca8fd343d
Revises: 5e5ccecb8bb5
Create Date: 2024-02-17 13:56:21.520765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263ca8fd343d'
down_revision = '5e5ccecb8bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mensaje', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('opciones', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('presupuesto', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('contacto', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('imagen', sa.LargeBinary(), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('apellido',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('apellido',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('imagen')
        batch_op.drop_column('contacto')
        batch_op.drop_column('presupuesto')
        batch_op.drop_column('opciones')
        batch_op.drop_column('mensaje')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
