"""empty message

Revision ID: 45f5d76a0eec
Revises: 263ca8fd343d
Create Date: 2024-02-17 17:53:04.049896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f5d76a0eec'
down_revision = '263ca8fd343d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propiedades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('num_banos', sa.Integer(), nullable=True),
    sa.Column('num_estacionamientos', sa.Integer(), nullable=True),
    sa.Column('num_habitaciones', sa.Integer(), nullable=True),
    sa.Column('imagen', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('propiedades')
    # ### end Alembic commands ###
