"""empty message

Revision ID: bb4816dc6426
Revises: 45f5d76a0eec
Create Date: 2024-02-17 17:58:35.690305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb4816dc6426'
down_revision = '45f5d76a0eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propiedades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('estacionamientos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('habitaciones', sa.Integer(), nullable=True))
        batch_op.drop_column('num_habitaciones')
        batch_op.drop_column('num_estacionamientos')
        batch_op.drop_column('num_banos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propiedades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_banos', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('num_estacionamientos', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('num_habitaciones', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('habitaciones')
        batch_op.drop_column('estacionamientos')
        batch_op.drop_column('banos')

    # ### end Alembic commands ###
